---
apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: practice-bowlorama
spec:
  container:
    image: nhcnessienyc/practice-bowlorama:0.0.1
  input: rolls
  idleTimeoutMs: 60000
  protocol: grpc
